#!/bin/bash

deviceID=$1

# Defining Directories
homeDirectory="$HOME"
binDirectory="$homeDirectory/bin/"
adbCompanionDir="$binDirectory/adbCompanion/"
adbServices="$adbCompanionDir/services/"

last_log="$adbServices/last_log"

finish() {
	lastLog=$(zenity --question --ellipsize --icon-name="document-open" --text "\nWould you like to \nopen the last log?" 2>/dev/null);

	case $? in
		"0")
			$last_log
			;;
		"1")
			;;
	esac
}

trap finish EXIT

adblog -s $deviceID -l


