#!/bin/bash

deviceID=$1

# Defining Directories
homeDirectory="$HOME"
binDirectory="$homeDirectory/bin/"
adbCompanionDir="$binDirectory/adbCompanion/"
adbServices="$adbCompanionDir/services/"

last_log="$adbServices/last_log"

finish() {
	lastLog=$(zenity --question --ellipsize --icon-name="document-open" --text "\nWould you like to \nopen the last log?" 2>/dev/null);

	case $? in
		"0")
			$last_log
			;;
		"1")
			;;
	esac
}

getLogs() {
	grepBool=$(zenity --question --ellipsize --text "\nWould you like to \ngrep this log?" 2>/dev/null);

	case $? in
		"0")
			input=$(zenity --title "adb_log" --entry --text "Enter the parameters, which will be implemented as:  'adblog | grep <input>'" 2>/dev/null)
			echo "$input"
			adblog -s $deviceID -l | grep "$input"
			;;
		"1")
			adblog -s $deviceID -l
			;;
	esac
}

trap finish EXIT

getLogs
