#!/bin/bash

# Defining Directories 
homeDirectory="$HOME"
binDirectory="$homeDirectory/bin/"
adbCompanionDir="$binDirectory/adbCompanion/"
adbCompanionSrc="$adbCompanionDir/src/"
adbServices="$adbCompanionDir/services/"

source $adbCompanionSrc/kv-bash/./kv-bash 

FILE_COUNT=1

sedparam='p'

$(kvget_system preferredEditor) `ls -t /scratch/logs/* | sed -n $FILE_COUNT$sedparam`&
