#!/bin/bash

# Defining Directories 
homeDirectory="$HOME"
binDirectory="$homeDirectory/bin/"
adbCompanionDir="$binDirectory/adbCompanion/"
adbCompanionSrc="$adbCompanionDir/src/"

# Defining Global Variables
initialSetupComplete="initialSetupComplete"
helpString="
Usages: adbcompanion [OPTIONS]
  Options:
     -h  | --help  : Prints this help message and exits
     -nu | --noupdate : Don't update master (one-time)
     -s  | --settings : Change settings including:
                          - Toggle Auto-Update
                          - Clear Device Names
                          - Uninstall adbCompanion
                          - Choose Preferred Editor
"

source $adbCompanionSrc/kv-bash/./kv-bash

inputArgs()
{	
	for arg in $@; do case $arg in
		--help|-h)
			echo -e "$helpString"
			exit 22
			;;
		D3gN0)
			kvset_system isUpdated "true"
			;;
		-nu | --noupdate)
			kvset_system noUpdate "true"
			;;
		-s | --settings)
			$adbCompanionSrc/setSettings
			exit 22
			;;
		*)
			echo -e "\n$arg is an unsupported command: See reference below"
			echo -e "$helpString"
			exit 22
		esac
	done
}

verify_server()
{
	# My server needs to be restarted with each new session
	# Unsure why, and probably an unneccesary step for most
	echo "Checking Device Permissions"
	
	if [[ $(adb devices | grep -w "no permissions") != "" ]]; then
		echo "User Currently Lacks Permissions: Restarting Server"
		eatOutput=$(adb kill-server)
		eatOutput=$(sudo adb start-server)
		echo "ADB Server Reset"
	fi
	
	echo
}

setupEditor() {
	if [[ $(kvget_system preferredEditor) == "" ]]; then
		$adbCompanionSrc/settings/preferred-editor
	fi 
}

versioning() {

	# GT version must be 1st argument
	version_gt() { test "$(printf '%s\n' "$@" | sort -V | head -n 1)" != "$1"; }

	version=$(cat $adbCompanionSrc/version)

	case $(kvget_system version) in
		"")
			kvclear
			kvset_system version $(cat $adbCompanionSrc/version)
			echo "Due to upgrades in the system, previous users will need to name their devices again"
			echo
			;;
	esac
}



######## Main Script Starts Here #########

versioning

# Handle all input arguments
inputArgs $@

# Only verify server after updating version, otherwise it is done twice
if [[ $(kvget_system isUpdated) == "true" || $(kvget_system noUpdate == "true") ]]; then
	verify_server
fi

setupEditor

