#!/bin/bash

# Defining Directories
homeDirectory="$HOME"
binDirectory="$homeDirectory/bin/"
adbCompanionDir="$binDirectory/adbCompanion/"
adbCompanionSrc="$adbCompanionDir/src/"

# Defining Global Variables
initialSetupComplete="initialSetupComplete"

source $adbCompanionSrc/kv-bash/./kv-bash

installZenity()
{	
	if [[ $(which zenity) == "" ]]; then
		#ask for user permission
		sudo apt-get install zenity
	fi
}

ln -s $adbCompanionDir/adbcompanion $binDirectory/adbcompanion

kvset $initialSetupComplete "true"
