#!/bin/bash

# Defining Directories 
homeDirectory="$HOME"
binDirectory="$homeDirectory/bin/"
adbCompanionDir="$binDirectory/adbCompanion/"
adbCompanionSrc="$adbCompanionDir/src/"

source $adbCompanionSrc/kv-bash/./kv-bash

######## Main Script Starts Here #########

cd $adbCompanionDir

restoreBranch()
{
	case $(kvget_system mostRecentBranch) in
		$(git branch | grep \* | cut -d ' ' -f2))
			return
			;;
		"")
			return
			;;
		*)
			git checkout $(kvget_system mostRecentBranch)
			;;
	esac	
}

restoreBranch

git stash pop

