#!/bin/bash

# Defining Directories 
homeDirectory="$HOME"
binDirectory="$homeDirectory/bin/"
adbCompanionDir="$binDirectory/adbCompanion/"
adbCompanionSrc="$adbCompanionDir/src/"

source $adbCompanionSrc/kv-bash/./kv-bash

######## Main Script Starts Here #########

cd $adbCompanionDir

restoreBranch()
{
	case $(kvget mostRecentBranch) in
		$(git branch | grep \* | cut -d ' ' -f2))
			return
			;;
		"")
			return
			;;
		*)
			git checkout $(kvget mostRecentBranch)
			;;
	esac	
}

restoreBranch

case $(kvget isStashPopped) in
	"true")
		kvset isStashPopped "false"	
		;;
	"false")
		git stash pop
		;;
esac
